name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./LuuaGorevPanosu
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./LuuaGorevPanosu
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: LuuaGorevPanosu
        path: ./LuuaGorevPanosu/bin/Release/net6.0/
